
baseURL = "https://pedal-r.com"
title = "PEdAL-R"
# copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 2
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
# theme = "hugo-theme-chunky-poster"


[menu]
  [[menu.main]]
    identifier = "viagens"
    name = "Viagens"
    url = "/viagens"
    weight = 1
  [[menu.main]]
    identifier = "loja"
    name = "Loja"
    url = "/3-loja/"
    weight = 0
  [[menu.main]]
    identifier = "fotos"
    name = "Fotos"
    url = "/2-fotos/"
    weight = 0
[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Hugo Authors"
  description = "Lorem ipsum dolor sit amet."
  homepageImage = "/images/homepage-image.jpg"
  icon = "img/pedalricone.png"
  logo = "img/pedalr.png"
  share = true
  showLanguageSwitcher = false
  inDevelopment = true

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["custom.css"]
  customJS = []

  [params.social]
    rss = true
    email = "example@example.com"
    facebook = "https://facebook.com"
    twitter = "https://twitter.com"
    linkedin = "https://linkedin.com"
    stack-overflow = "https://stackoverflow.com"
    instagram = "https://stackoverflow.com"
    github = "https://github.com"
    weibo = "https://www.weibo.com"
    medium = "https://medium.com"
    pinterest = "https://pinterest.com"
    reddit = "https://reddit.com"
    gitlab = "https://gitlab.com"
    mastodon = "https://mastodon.social"
    keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
