baseURL = "https://pedal-r.com/"
title = "Pedal-R"
# copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 2
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
# theme = "hugo-theme-chunky-poster"

[languages]
  [languages.pt-br]
    DefaultContentLanguage = "pt-br"
    weight = 1
    [languages.pt-br.params]
      # description = "What we see while we ride"
  [languages.en]
    DefaultContentLanguage = "en"
    weight = 2
    [languages.en.params]
      # description = "What we see while we ride"
      # [languages.en.params.navigation]
      #   help = "Aide"

[menu]
  [[menu.main]]
    identifier = "viagens"
    name = "Viagens"
    url = "/viagens"
    weight = 1
  # [[menu.main]]
  #   identifier = "loja"
  #   name = "Loja"
  #   url = "/loja/"
  #   weight = 0
  [[menu.main]]
    identifier = "fotos"
    name = "Fotos"
    url = "/fotos/"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[params]
  author = "PEdAL-R"
  description = "What we see while we ride"
  icon = "img/pedalricone.png"
  logo = "img/pedalr.png"
  share = true
  showLanguageSwitcher = true
  inDevelopment = true

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["custom.css"]
  customJS = ["custom.js"]

  [params.social]
    email = "contato.pedalr@gmail.com"
    instagram = "https://instagram.com/pedal.r_"
    # youtube = "https://www.youtube.com/user/jeandivision"
    spotify = "https://open.spotify.com/playlist/0fuoTFnmTga62x2ZMvOMf2?si=oeVasRE3RceDSyOdB5PTbA"
    # github = "https://github.com/jenmchl/pedal-r"

  [[params.contributors]]
    name = "Jean Michel"
    insta = "jeanmichelf"
  [[params.contributors]]
    name = "Douglas Coelho"
    insta =  "ruivo138"
  [[params.contributors]]
    name = "Bárbara Hartmann"
    insta =  "bahartma"
  [[params.contributors]]
    name = "Bruno Lourenço"
    insta =  "bruunolouurenco"
  [[params.contributors]]
    name = "Gianfranco Vacani"
    insta =  "gianfranco.vacani"
  [[params.contributors]]
    name = "Guilherme Akio"
    insta =  "akiooika"
  [[params.contributors]]
    name = "Suryan Cury"
    insta =  "sussuryan"
  [[params.contributors]]
    name = "Roberto Bicicletas"
    insta =  "rainorshinecycles"
  [[params.contributors]]
    name = "Luis Felipe Cagliari"
    insta =  "luisfelipeogro"
  [[params.contributors]]
    name = "Julia Jubileu"
    insta =  "julia.jubileu"
  [[params.contributors]]
    name = "Caleb Candido"
    insta =  "calebcandido"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
